### PR TITLE
Bug: form link is used as title #305

### LINKED ISSUE #305: Bug: form link is used as title
### Issue Type

Bug

### Summary

if the form doesn't have a text as 1st row, the link is used as title

### Priority

Blocker

### Description

Based on the work done in issue #273, the block now is getting the 1st row as title, without checking if it has regular text or not.

Because the previous setup doesn't have the text in the block, now all v2-custom form blocks without it are broken.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

any

### Steps to Reproduce

https://main--vg-macktrucks-com--volvogroup.aem.live/block-library/blocks/v2-custom-form
all the variants are affected

### Expected Results

https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/form/title-in-block-form
the text is used as title

### Actual Results

Image
the config url is used as title

### Attachment

_No response_

### PR DESCRIPTION
**Pull request by jonatan-lledo-netcentric**
# Bug fix

After fixing an issue to hide the title text after submitting the v2 custom form block, the block is set up to have as 1st row the title text. In the library is not set as this, so to be able to have it, this fix checks if the 1st row in the block has the config json link to add the title dynamically

#

Fix #305 

Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/form/title-in-block-form
- After: https://305-form-link-is-used-as-title--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/form/title-in-block-form

Library:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-custom-form
- After: https://305-form-link-is-used-as-title--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-custom-form

### CODE REVIEW

**Review by santi-homps — APPROVED** [review]

File: blocks/v2-custom-form/v2-custom-form.js [hunk 1]
```diff
@@ -618,6 +618,7 @@ export default async function decorate(block) {
   const formLink = block.querySelector('a[href$=".json"]');
   const thankYouPage = [...block.querySelectorAll('a')].filter((a) => a.href.includes('thank-you'));
   const formTitleContainer = block.querySelector(':scope > div:first-child > div');
+  const hasFormLink = formLink && formTitleContainer.contains(formLink);
```
Comment (alan-le-bihan) [inline blocks/v2-custom-form/v2-custom-form.js:621]: Let's give a more descriptive name for this variable: `isFormLinkInsideTitleContainer`

File: blocks/v2-custom-form/v2-custom-form.js [hunk 2]
```diff
@@ -628,8 +629,8 @@ export default async function decorate(block) {
     }
     // clean the content block before appending the form
     block.innerText = '';
-    // add again the content text after the block clean
-    if (formTitleContainer) {
+    // add again the content text after the block clean only if the 1st child is not the config form link
```
Comment (alan-le-bihan) [inline blocks/v2-custom-form/v2-custom-form.js:632]: I’d suggest removing that comment since the code below is self-explanatory.
