### PR TITLE
Bug: Magazines on the Mack Trucks disappeared for the New Zealand site #292

### LINKED ISSUE #292: Bug: Magazines on the Mack Trucks disappeared for the New Zealand site
### Issue Type

Bug

### Summary

Explore Articles

### Priority

Blocker

### Description

HI Team,

We have published more than 100 Magazine articles for Mack trucks New Zealand site. But none are appearing on the 
explore articles page: https://www.macktrucks.co.nz/magazine/explore-articles

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All Browsers

### Steps to Reproduce

Navigate to https://www.macktrucks.co.nz/magazine/explore-articles
The page looks empty

### Expected Results

Artilces list should appear as shown on the Mack Trucks US site:
https://www.macktrucks.com/magazine/explore-articles

### Actual Results

Image

### Attachment

_No response_

### PR DESCRIPTION
**Pull request by santi-homps**
**NOTES:** 

- This fixes the block not being able to get all articles and instead gets 100 as a default. 
- The correct way would be to modify the current one so that it only get 4 but this would take longer and the bug is in production already
- There is already a V2 block to replace this correctly but its not being used yet.

With that in mind I think its best for us to just merge this into main and decide what are the next steps regarding this page

Fix #292

Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/magazine/explore-articles
- After: https://292-magazines-nz--vg-macktrucks-com--volvogroup.aem.page/magazine/explore-articles

Other markets:

New Zaeland:

- Before: https://main--macktrucks-co-nz--volvogroup.aem.page/magazine/explore-articles
- After: https://292-magazines-nz--macktrucks-co-nz--volvogroup.aem.page/magazine/explore-articles

### CODE REVIEW

File: blocks/explore-articles/explore-articles.js [hunk 1]
```diff
@@ -32,6 +32,9 @@ const getOptions = (list, placeholder) => {
   list.forEach((el) => {
     const option = createElement('option', { props: { value: el } });
     option.innerText = capitalizeWords(el);
+    if (el == 0) {
```
Comment (jonatan-lledo-netcentric) [inline blocks/explore-articles/explore-articles.js:35]: Please, remove this because that's how we know that the `search.xlsx` file has 2 tabs, and it has to have only 1 to fix it

**Review by jonatan-lledo-netcentric — APPROVED** [review]

File: blocks/explore-articles/explore-articles.js (hunk 1 above)
Comment (santi-homps) [reply blocks/explore-articles/explore-articles.js]: done

File: scripts/services/magazine.service.js [hunk 2]
```diff
@@ -8,7 +8,7 @@ import { fetchData, magazineSearchQuery, TENANT } from '../search-api.js';
  * @returns {Promise<Array>} - A promise that resolves to an array of articles and facets.
  */
 export const fetchMagazineData = async ({
-  limit,
+  limit = 100,
```
Comment (alan-le-bihan) [inline scripts/services/magazine.service.js:11]: What if we have more than 100 articles?

Comment (alan-le-bihan) [inline scripts/services/magazine.service.js:11]: What if there are more than 100 articles?

Comment (jonatan-lledo-netcentric) [reply scripts/services/magazine.service.js:11]: Then we have an error in Graphql, so we have to ask in chunks of 100 max using the offset attribute

**Review by alexiscoelho — APPROVED** [review]

**Review by alan-le-bihan — APPROVED** [review]
