### PR TITLE
Bug: [v2-trucks-lineup] #65

### LINKED ISSUE #65: Bug: [v2-trucks-lineup]
### Description

- [ ] As a content editor, I should be able to define either one or multiple links below the truck name (v2-trucks-lineup block). It currently only is possible to define two links. If only one link is set, the design breaks.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices. 

### Steps to Reproduce

1. Navigate to https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B7EB5FD43-7498-4DD4-B598-F6225CDA8339%7D&file=index.docx&action=default&mobileredirect=true
2. On the truck lineup carousel block, scroll to Mack LR truck model for example. See how if you try to remove the period after the "Refuse" segment link, it breaks the block and causes the first image in the Actual Results screen shot list. 
3. Also see how the segment links are red color when they should be bolded black as shown in the Figma designs. 

### Expected Results

Figma: https://www.figma.com/design/IAwrZWSP4gUrZdrsvZxgmA/Final-pages?node-id=2-5381&t=NS5NzDgUH7T7vx3E-1

Image

*Although the above example has 2 segment options, the block should work with only 1 to give the same desired design result. 

### Actual Results

1. Current page with period after segment link which is the only way we can get the block to work with 1 segment without breaking it. 

Image
Image

2. If you try to remove the period after the segment link, it breaks the block as seen below:

Image
Image

### Related tickets
https://github.com/Netcentric/vg-macktrucks-com-rd/issues/13
https://github.com/Netcentric/vg-macktrucks-com-rd/pull/82

### PR DESCRIPTION
**Pull request by jonatan-lledo-netcentric**
# Bugfix

Now it is not needed to add any dirty workaround to the link to make it not a button. For comparison, I left the demo page and the current one that still has the dot in a single link

#
Fix #65 

Test URLs:

With the dot (scroll to the truck line up)
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/
- After: https://65-v2-trucks-lineup--vg-macktrucks-com--volvogroup.aem.page/

without the dot
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/lineup-demo
- After: https://65-v2-trucks-lineup--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/lineup-demo

### CODE REVIEW

File: blocks/v2-truck-lineup/v2-truck-lineup.js [hunk 1]
```diff
@@ -212,6 +212,13 @@ export default async function decorate(block) {
     const descriptions = tabContent.querySelectorAll('p:not(.button-container)');
     [...descriptions].forEach((description) => description.classList.add(`${blockName}__description`));
 
+    if (!descriptions || descriptions.length === 0) {
+      const buttonLink = tabContent.querySelector('.button-container:has(:not(.button))');
```
Comment (alan-le-bihan) [inline blocks/v2-truck-lineup/v2-truck-lineup.js:216]: Let's rename `buttonLink` to `buttonContainer` as it's not a link.

**Review by alan-le-bihan — APPROVED** [review]
