### PR TITLE
Bug: Web version of the Dealer Locator shows incorrect distance #390

### LINKED ISSUE #390: Bug: Web version of the Dealer Locator shows incorrect distance
### Issue Type

Bug

### Summary

_No response_

### Priority

Blocker

### Description

The app versions are correct in showing miles from Dubuque. On the web version from desktop/laptop, the distance is off by 30 miles for RDO and other locations outside RDO. When clicking on directions the real miles show-up. The initial mile shown is off.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Navigate to https://www.macktrucks.com/buy-mack/find-a-dealer/
2. Search for or select an RDO or other non-RDO location.
3. Observe the mileage displayed next to the location name.
4. Click on Directions.
5. Compare the initially shown mileage with the mileage shown on the directions page.

### Expected Results

Distance shown initially should match the real distance shown under Direction

### Actual Results

Shows incorrect distance. 

### Attachment

Image

Image

### PR DESCRIPTION
**Pull request by santi-homps**
Although not all markets are listed below, this change will affect all of them. I added just the 3 main ones and some other examples that are different from each other.

Also fixed the hover effect on the pins so that the scaled version stays on point

Fix #390 

USA (should be miles by default):
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://390-distance-calc--vg-macktrucks-com--volvogroup.aem.page/buy-mack/find-a-dealer/

Canada:
- Before: https://main--macktrucks-ca--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://390-distance-calc--macktrucks-ca--volvogroup.aem.page/buy-mack/find-a-dealer/

Mexico:
- Before: https://main--macktrucks-com-mx--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://390-distance-calc--macktrucks-com-mx--volvogroup.aem.page/buy-mack/find-a-dealer/

### Other markets:

Australia:
- Before: https://main--macktrucks-com-au--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://390-distance-calc--macktrucks-com-au--volvogroup.aem.page/buy-mack/find-a-dealer/

Bahamas (this one should default to miles):
- Before: https://main--macktrucks-bs--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://390-distance-calc--macktrucks-bs--volvogroup.aem.page/buy-mack/find-a-dealer/

Chile:
- Before: https://main--macktrucks-cl--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://390-distance-calc--macktrucks-cl--volvogroup.aem.page/buy-mack/find-a-dealer/

### CODE REVIEW

**Comment by alan-le-bihan** [comment]
@santi-homps The DL isn't loading anything for me in some markets, do you know why?

File: blocks/dealer-locator/sidebar-maps.js [hunk 1]
```diff
@@ -1531,7 +1531,7 @@ $.fn.sortedPins = function () {
   for (var i = 0; i < $pinLength; i++) {
 
     $pins[i];
-    $pins[i].distance = $.fn.getDistanceInKm([$pins[i].MAIN_LATITUDE, $pins[i].MAIN_LONGITUDE]);
+    $pins[i].distance = $.fn.getDistanceInMiles([$pins[i].MAIN_LATITUDE, $pins[i].MAIN_LONGITUDE]);
```
Comment (jonatan-lledo-netcentric) [inline blocks/dealer-locator/sidebar-maps.js:1534]: What happens if we swap to km instead? Is another function?

**Comment by alan-le-bihan** [comment]
Screenshot 2025-07-30 at 09 37 43

Does this button have any purpose now?

**Review by jonatan-lledo-netcentric — APPROVED** [review]

File: blocks/dealer-locator/sidebar-maps.js (hunk 1 above)
Comment (santi-homps) [reply blocks/dealer-locator/sidebar-maps.js:1534]: no, its the same function... if you see below the variables on the top you'll see the 2 different factors... if we display miles its set to 1 and if its kms we multiply miles by 1.6 (aprox.)

File: blocks/v2-dealer-locator/versions/default/sidebar-maps.js [hunk 2]
```diff
@@ -236,14 +236,14 @@ var $distanceToggles = $('.toggle-container');
     $directionsDisplay = new google.maps.DirectionsRenderer();
 
     google.maps.event.addListener(
-        $directionsDisplay,
-        'routeindex_changed',
-        function () {
+      $directionsDisplay,
+      'routeindex_changed',
+      function () {
```
[the remark this answers is not in the document]
Comment (santi-homps) [reply blocks/v2-dealer-locator/versions/default/sidebar-maps.js:241]: yes we can... although there are a lot of unused parts of the code and I dont usually touch them (just in case). Here the formatting made some changes for me

**Comment by santi-homps** [comment]
> @santi-homps The DL isn't loading anything for me in some markets, do you know why?

maybe you dont have accepted the location detection... that causes some issues in some of them

**Review by nagarajnetcentric — APPROVED** [review]

**Review by alan-le-bihan — APPROVED** [review]
