### PR TITLE
MT Java Script errors #25

### LINKED ISSUE #25: MT Java Script errors
### Issue Type

Bug

### Summary

JavaScript errors found via Adobe RUM report

### Priority

Medium

### Description

See attached file for details on the error sources and the error lines and fix each.  
[MT site_Java Script Errors_Adobe RUM report_11122024.xlsx](https://github.com/user-attachments/files/17720347/MT.site_Java.Script.Errors_Adobe.RUM.report_11122024.xlsx)

Adobe RUM report: https://www.aem.live/tools/rum/explorer.html?domain=www.macktrucks.com&filter=&view=month&checkpoint=error&domainkey=37FC6C63-F3B0-4769-B988-908061F718DE

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

_No response_

### Steps to Reproduce

_No response_

### Expected Results

No JavaScript errors.

### Actual Results

_No response_

### Attachment

_No response_

### Notes
- **Check for the updated report when working on this ticket, since it was created a while ago.**

### PR DESCRIPTION
**Pull request by jonatan-lledo-netcentric**
# BugFixes

There are several pages affected, so any errors in the report or found during this development have been addressed in this update. Some of them are just failsafe code because I was unable to reproduce some of them, but the newly founded ones are reproducible in the console in the live version.

- v2-custom-form: null evaluating 'form.closest'. (not reproduced)
- v2-truck-lineup: null reading 'parentNode' (not reproduced)
- header: null evaluating 'closest' (not reproduced)
- sidebar-maps: error when geolocation is not allowed
- v2-specifications: error in the header data set

Fix #25

Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/
- After: https://25-javascript-errors--vg-macktrucks-com--volvogroup.aem.page/

- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/info/driven-by-heroes
- After: https://25-javascript-errors--vg-macktrucks-com--volvogroup.aem.page/info/driven-by-heroes

- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://25-javascript-errors--vg-macktrucks-com--volvogroup.aem.page/buy-mack/find-a-dealer/

- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/buy-mack/incentives/
- After: https://25-javascript-errors--vg-macktrucks-com--volvogroup.aem.page/buy-mack/incentives/

- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/live-tour/#faqs
- After: https://25-javascript-errors--vg-macktrucks-com--volvogroup.aem.page/live-tour/#faqs

- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/powertrain-and-suspensions/transmissions/mdrive-hd/
- After: https://25-javascript-errors--vg-macktrucks-com--volvogroup.aem.page/powertrain-and-suspensions/transmissions/mdrive-hd/

### CODE REVIEW

File: blocks/header/header.js [hunk 1]
```diff
@@ -317,9 +335,15 @@ const onAccordionItemClick = (el) => {
   const isExpanded = menuEl.classList.contains(`${blockName}__menu-open`);
   el.currentTarget.setAttribute('aria-expanded', isExpanded);
 
-  if (isDesktop && isMainLink) {
+  if (!isDesktop) {
+    return;
+  }
+
+  console.warn('if is not a desktop viewport, the menu will not be opened');
```
Comment (alexiscoelho) [inline blocks/header/header.js:342]: remove this console.log please

File: blocks/v2-dealer-locator/versions/default/sidebar-maps.js [hunk 2]
```diff
@@ -2658,7 +2662,7 @@ $.fn.setLocation = function () {
     }, function () {
 
       //this.setMap(null);
-      console.log('error with navigator');
+      console.log('getCurrentPosition [error function triggered]: %cError with navigator. Geolocation could be disabled', 'color: red;');
```
Comment (alexiscoelho) [inline blocks/v2-dealer-locator/versions/default/sidebar-maps.js:2665]: shouldn't this be a console.error or console.warn?

File: blocks/v2-truck-lineup/v2-truck-lineup.js [hunk 3]
```diff
@@ -146,25 +149,36 @@ const arrowFragment = document.createRange().createContextualFragment(`<li>
...
-  descriptionContainer.classList.add(`${blockName}__description-container`);
-
   const tabItems = block.querySelectorAll(':scope > div > div');
 
   const imagesWrapper = createElement('div', { classes: `${blockName}__slider-wrapper` });
   const imagesContainer = createElement('div', { classes: `${blockName}__images-container` });
-  descriptionContainer.parentNode.prepend(imagesWrapper);
   imagesWrapper.appendChild(imagesContainer);
+  descriptionContainer.classList.add(`${blockName}__description-container`);
+  block.prepend(imagesWrapper);
```
Comment (alexiscoelho) [inline blocks/v2-truck-lineup/v2-truck-lineup.js:158]: Are you sure about this change? A bit different than the original...

**Review by alexiscoelho — CHANGES_REQUESTED** [review]

File: blocks/v2-truck-lineup/v2-truck-lineup.js (hunk 3 above)
Comment (jonatan-lledo-netcentric) [reply blocks/v2-truck-lineup/v2-truck-lineup.js:158]: descriptionContainer.parentNode = block. I checked it

File: blocks/header/header.js (hunk 1 above)
Comment (jonatan-lledo-netcentric) [reply blocks/header/header.js]: done

File: blocks/v2-dealer-locator/versions/default/sidebar-maps.js (hunk 2 above)
Comment (jonatan-lledo-netcentric) [reply blocks/v2-dealer-locator/versions/default/sidebar-maps.js:2665]: `warn` is more logical here. Done

File: mack-news/com/feed.xml [hunk 4]
```diff
@@ -2,7 +2,7 @@
 <feed xmlns="http://www.w3.org/2005/Atom">
```
Comment (alexiscoelho) [inline mack-news/com/feed.xml:2]: Are these two xml file changes suppose to be here?

File: blocks/v2-dealer-locator/versions/default/sidebar-maps.js [hunk 5]
```diff
@@ -2588,13 +2588,17 @@ $.fn.setLocation = function () {
         position.coords.longitude
       ];
 
-      $map.setCenter(pos);
-      $map.setZoom(8);
+      if ($map) {
+        $map.setCenter(pos);
+        $map.setZoom(8);
+      } else {
+        console.log('%cmap not set', 'color: red;');
```
Comment (alexiscoelho) [inline blocks/v2-dealer-locator/versions/default/sidebar-maps.js:2595]: console.log?

**Review by alexiscoelho — CHANGES_REQUESTED** [review]

File: mack-news/com/feed.xml (hunk 4 above)
Comment (jonatan-lledo-netcentric) [reply mack-news/com/feed.xml]: I revert them, maybe added because the branch merging

**Review by alexiscoelho — APPROVED** [review]

**Review by alan-le-bihan — APPROVED** [review]
